add support for prometheus metrics
iv-org/invidious-companion pull request #25
Opened 2024-12-18 03:18 UTC by Fijxu

Useful for troubleshooting blockages in a visual manner using Grafana.

It doesn't count how many times `poTokenGenerate` has failed between lines 69-83, I didn't wanted to touch that much code. But I'll make a new commit to count on those lines too so you can review it.

2024-12-18 07:38 UTC, unixfox commented
Maybe you can includes some "default" dashboards :)

2025-03-16 15:02 UTC, unixfox commented
Could you allow this to be toggleable? I think people running private instances don't need it, it's more towards public instances.

2025-03-18 19:46 UTC, Fijxu commented
This should be better, tell me if you want to change or add something

2025-03-19 11:36 UTC, unixfox requested changes

2025-03-19 11:36 UTC, unixfox commented on deno.json
> +    "metrics": "./src/lib/helpers/metrics.ts",
you don't need to define metrics in the deno.json. We define some .ts file like this because we allow those files to be overridden using imports, but here you are not allowing that.

https://github.com/iv-org/invidious-companion/blob/8b967d5d39fe5782e63f395091070b6c50606fab/src/lib/helpers/youtubePlayerHandling.ts#L6-L17

2025-03-20 03:30 UTC, alexmaras requested changes
I'm going to pull this down and test it too, but here's some comments in the mean time. Nothing looks wildly problematic.

2025-03-20 03:30 UTC, alexmaras commented on src/routes/index.ts
> +    app.route("/metrics", metrics_);
can we only register this route if `config.server.enable_metrics` is true?

2025-03-20 03:30 UTC, alexmaras commented on src/routes/metrics.ts
> +
if you've done `metrics_` here in order to get around it clashing with `metrics`, you can do one of two things:
1. swap to using the Hono Context to pass the metrics object around, then use `c.get('metrics').register.metrics()` here, and change code accordingly throughout
2. use `import { metric as metricHelper } from` here

I slightly prefer option 1, as it means that using it in any route is possible without having to add a new `import`, which is just a bit simpler.

2025-03-20 03:30 UTC, alexmaras commented on src/main.ts
> +                }
this swallows the error and prevents the backoff schedule from working. You need to rethrow the error in the `catch` if you're going to wrap this. 

```suggestion
                try {
                    ({ innertubeClient, tokenMinter } = await poTokenGenerate(
                        innertubeClient,
                        config,
                        innertubeClientCache,
                    ));
                } catch (err) {
                    metrics?.potokenGenerationFailure.inc();
                    throw err;
                }
```

or alternatively

```suggestion
                  ({ innertubeClient, tokenMinter } = await poTokenGenerate(
                      innertubeClient,
                      config,
                      innertubeClientCache,
                  ).catch((err) => {
                      metrics?.potokenGenerationFailure.inc();
                      throw err;
                  }));
```

Both of these are untested, but something like this needs to happen

2025-03-20 03:30 UTC, alexmaras commented on src/lib/helpers/metrics.ts
> +        return;
```suggestion
```
No need to add empty returns

2025-03-20 03:30 UTC, alexmaras commented on src/lib/helpers/metrics.ts
> +        }
are we expecting `"Sign in to confirm you’re not a bot"` and `"This helps protect our community"` to sometimes happen on the same request? If so, this structure is necessary, otherwise it could be restructured into an `if/else`.

If you have to keep this structure, you can strip the `: boolean` form the `hit` definition and do `if (!hit)` easily enough. Not a big deal.

2025-03-20 04:08 UTC, Fijxu commented on src/lib/helpers/metrics.ts
> +        }
>are we expecting "Sign in to confirm you’re not a bot" and "This helps protect our community" to sometimes happen on the same request?

Yes, `"Sign in to confirm you’re not a bot"` is the reason, and `"This helps protect our community"` is the subreason of `"Sign in to confirm you’re not a bot"`

Now that I think it, it should be better to check if :

```
if (
    videoData.playabilityStatus?.reason?.includes(
        "Sign in to confirm you’re not a bot",
    )
) {
    if (
        videoData.playabilityStatus?.errorScreen?.playerErrorMessageRenderer
        ?.subreason?.runs?.[0]?.text?.includes(
            "This helps protect our community",
        )
    ) {
        this.innertubeErrorSubreasonProtectCommunity.inc();
        hit = true;
    }
    this.innertubeErrorReasonSignIn.inc();
    hit = true;
}
```

Or something like that. And somehow replace `this.innertubeErrorUnknown.inc();` by `this.innertubeErrorReasonUnknown.inc();` `this.innertubeErrorSubreasonUnknown.inc();` to be able to keep track of unknown reason and subreasons separately. There is more reasons and subreasons like sensitive content, age restricted videos, unavailable videos, etc, but I don't think is really worth adding those to the metrics. I think those have to be checked and ignore those errors (because they are not really errors, just restrictions) if they are present in the `videoData.playabilityStatus?` object

2025-03-20 04:43 UTC, alexmaras commented on src/lib/helpers/metrics.ts
> +        }
thanks for the context. Sounds like a reasonable restructure, yeah.

2025-03-20 12:05 UTC, alexmaras commented on src/lib/helpers/metrics.ts
> +    );
```suggestion
    public innertubeSuccessfulRequest = this.createCounter(
        "innertube_successful_request",
        "Number of successful requests made to the Innertube API",
    );
```

2025-03-20 13:30 UTC, alexmaras commented
Just an update - pulled the branch and tested with prometheus and things look like they're correctly read in, so the format of the output all looks good.

2025-03-20 21:19 UTC, Fijxu commented on src/main.ts
> +                }
Done. I added `throw new Error("xd")` to test and I get `Exception in cron handler regenerate youtube session Error: xd`. Is that the correct output?

2025-03-21 00:47 UTC, alexmaras commented on src/main.ts
> +                }
I'll test it out too, but that sounds right, yeah.

2025-03-21 01:01 UTC, alexmaras requested changes

2025-03-21 01:01 UTC, alexmaras commented on src/routes/index.ts
> +        app.route("/metrics", metrics_);
you can rename this to just `metrics` now

2025-03-21 01:01 UTC, alexmaras commented on src/lib/helpers/youtubePlayerHandling.ts
> +import { metrics } from "../helpers/metrics.ts";
now that you're passing it in the Hono context, just grab this with `c.get("metrics")`

2025-03-21 01:01 UTC, alexmaras commented on src/main.ts
> +initMetrics(config);
now that you're passing this in the hono context, we're probably best off changing this so it just created the object itself:

```suggestion
const metrics = config.server.enable_metrics ? new Metrics() : undefined
```
and drop `initMetrics` and the ability to use `metrics` straight from an import entirely.

2025-03-21 01:01 UTC, alexmaras commented on src/lib/helpers/metrics.ts
> +        }
this is tricky, I'm going to have a play with this and see if I can find a nice way to do it that feels like it'll extend a bit more easily without becoming impossible to understand.

2025-03-21 02:22 UTC, alexmaras commented on src/main.ts
> +                }
Yep, this works

2025-03-21 02:23 UTC, alexmaras commented on src/lib/helpers/metrics.ts
> +        }
This is the only bit I'm stuck on now, the rest of the PR looks good to me. I'm playing around with some options, these kinds of logical mazes are always painful to parse and implement.

2025-03-27 20:25 UTC, unixfox commented
Please rebase thank you :)

2025-03-27 20:26 UTC, unixfox commented on config/config.example.toml
> +# enable_metrics = false # env variable: ENABLE_METRICS
Same as https://github.com/iv-org/invidious-companion/pull/65, please rename to SERVER_ENABLE_METRICS

2025-03-27 20:30 UTC, unixfox requested changes

2025-03-27 20:30 UTC, unixfox commented on deno.json
> +    "prom-client": "npm:prom-client@15.1.3",
I would really like to avoid npm as much as possible, would it be possible for you to point to the github repo: https://github.com/siimon/prom-client/blob/v15.1.3/index.js?

You may use https://esm.sh to help you.

Using npm in deno requires enabling many many useless environment variables that I would like to get rid of at some point if we can stop using jsdom from npm.

2025-03-27 20:53 UTC, Fijxu commented
I'll add a default Grafana dashboard, do not merge it yet ;)

2025-03-27 21:23 UTC, unixfox commented on src/lib/helpers/metrics.ts
> +        }
interested too in a "better" format

2025-03-27 22:30 UTC, Fijxu commented on src/lib/helpers/metrics.ts
> +        }
Done, this looks better, unless you want to do the checking inside the own `checkStatus`, `checkReason` and `checkSubreason` functions.

2025-03-28 07:44 UTC, unixfox requested changes

2025-03-28 07:44 UTC, unixfox commented on src/lib/helpers/config.ts
> +                : Deno.env.get("SERVER_ENABLE_METRICS") === "false"
Why do you check for enable metrics env to be false?

If you remove the parameter it's false by default.

2025-03-28 10:40 UTC, alexmaras commented on src/lib/helpers/config.ts
> +                : Deno.env.get("SERVER_ENABLE_METRICS") === "false"
yeah, default of `Deno.env.get("SERVER_ENABLE_METRICS") === "true"` will make it a boolean correctly. At the moment it'd always be true unless the env variable `SERVER_ENABLE_METRICS` is `"false"`

2025-03-29 01:32 UTC, alexmaras approved these changes
I'm happy with this now. Will leave to @unixfox to check over the last changes.

2025-04-04 11:22 UTC, unixfox commented
Could you please rebase? Thanks

2025-04-04 15:41 UTC, Fijxu commented
Done

2025-04-05 00:56 UTC, merged