Add Invidious's download endpoint
iv-org/invidious-companion pull request #41
Opened 2024-12-27 06:30 UTC by syeopite

This PR adds support for Invidious's download endpoint to companion.

It doesn't however force the download of the video. The /videoplayback endpoint that the handler eventually redirects to will need to add the Content-Disposition like so to enforce that behavior

```
Content-Disposition: attachment; filename=${someFilename}
```

Subtitles also aren't supported yet as that'll require porting over Invidious's captions endpoint

Closes #13

2025-03-08 17:12 UTC, unixfox commented
can you rebase please :)?

2025-03-20 01:14 UTC, alexmaras commented on src/routes/invidious_routes/download.ts
> +        const videoId = body.get("id") as string | undefined;
```suggestion
        const videoId = body.get("id")?.toString();
```
This avoids overriding the type manually and results in the same outcome.

2025-03-20 01:15 UTC, alexmaras commented on src/routes/invidious_routes/download.ts
> +                (body.get("download_widget") as string || undefined) || "",
```suggestion
                body.get("download_widget").toString() || "",
```

2025-03-20 01:21 UTC, alexmaras commented on src/routes/invidious_routes/download.ts
> +        } else if (downloadWidgetData.itag) {
it might be worth defining a `zod` schema for this to strongly type and check this, see `config.ts` as an example. In particular it seems like either `label` or `itag` must be provided, which we can do in Zod directly.

2025-03-20 01:22 UTC, alexmaras commented on src/routes/invidious_routes/download.ts
> +            !(title || videoId || downloadWidgetData)
I think this is only checking that _any_ of the three values are available. Is that the intent? 
At the moment, this equates to:
"if title is truthy or videoId is truthy or downloadWidgetData is truthy"
If you want all three it'd have to be
```typescript
            !(title && videoId && downloadWidgetData)
```

2025-03-20 03:39 UTC, syeopite commented on src/routes/invidious_routes/download.ts
> +            !(title || videoId || downloadWidgetData)
Oops that's embarrassing 😅

2025-03-20 05:02 UTC, alexmaras requested changes
Some very minor stuff after the change to zod, I'm going to pull this down and test it out too. Thanks :+1:

2025-03-20 05:02 UTC, alexmaras commented on src/routes/invidious_routes/download.ts
> +            const itag = Number(downloadWidgetData.itag);
```suggestion
            const itag = downloadWidgetData.itag;
```
`zod` is already validating this as a number now, so you can drop the Number constructor.

2025-03-20 05:02 UTC, alexmaras commented on src/routes/invidious_routes/download.ts
> +            const filename = `${title}-${videoId}.${ext || ""}`;
```suggestion
            const filename = `${title}-${videoId}.${ext}`;
```
Seeing as `zod` is making sure this is a string, this doesn't need the check anymore. If it's falsey, it's because it's an empty string anyway.

2025-03-20 05:02 UTC, alexmaras commented on src/routes/invidious_routes/download.ts
> +                encodeURIComponent(filename),
does this need encoding? `URLSearchParams` already URL encodes things when they go through `toString()`:

![image](https://github.com/user-attachments/assets/ceef58be-fed0-476c-8daf-8e75623d0eb3)

2025-03-20 05:02 UTC, alexmaras commented on src/routes/videoPlaybackProxy.ts
> +        }"; filename*=UTF-8''${encodeRFC5987ValueChars(title)}`;
wow, what a weird format. Nice work, good to have the link to the MDN doc in the comment on that other file :+1:

2025-03-20 05:06 UTC, alexmaras commented on src/routes/invidious_routes/download.ts
> +const DownloadWidgetSchema = z.discriminatedUnion("ext", [
this throws an error on launch. I believe the discriminate union needs literals to work properly, because it can determine the type entirely through those literals. 

In this case, I think you can just do `.or` to join the two

2025-03-20 05:31 UTC, alexmaras commented
![image](https://github.com/user-attachments/assets/0b2a9b72-fef6-47eb-888e-ddf2c5931aac)
seems to be working well with my test video. I just had to change the endpoint that the form submission targets to be companion rather than invidious. 

I'll keep testing for a bit longer with a bunch of itags, and I'll let @unixfox approve once they're happy. All looking good to me.

2025-03-20 05:34 UTC, alexmaras approved these changes
@unixfox I'll leave it to you to look through and approve/merge. See if you spot anything I've missed.

2025-03-20 05:39 UTC, syeopite commented on src/routes/invidious_routes/download.ts
> +            // "title" for compatibility with how Invidious sets the content deposition header
```suggestion
            // "title" for compatibility with how Invidious sets the content disposition header
```

2025-03-21 22:46 UTC, merged